### ISSUE TITLE
BCUninstaller will crash while loading up

### ISSUE THREAD

**Issue by TempUser13** [Klocman/Bulk-Crap-Uninstaller#222]
The application throws a error
![crash](https://user-images.githubusercontent.com/44703839/47919730-01bf8200-dea8-11e8-88ef-4f572732f927.png)

Target site = "Void <InitiateListRefresh>g__OnRefreshFinished|0(System.Object, System.Windows.Forms.FormClosedEventArgs) @ BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater+<>c__DisplayClass31_0"

Application ="BCUninstaller.exe [4.11.0.37815]"

![crash2](https://user-images.githubusercontent.com/44703839/47919844-62e75580-dea8-11e8-98c8-b1aa2c3160e9.PNG)
Clicking on stack trace: "
at BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater.<>c__DisplayClass31_0.<InitiateListRefresh>g__OnRefreshFinished|0(Object sender, FormClosedEventArgs args)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

hopefully this is what you actually need

**Comment by Klocman** [comment]
Can you click on the System.ArgumentException in the second image and copy the stack trace from that?

**Comment by TempUser13** [comment]
![capture crash2](https://user-images.githubusercontent.com/44703839/47921823-6f21e180-dead-11e8-9689-2d449322ed8f.PNG)

Message: "Invalid Unicode code point found at index 65. Parameter name: strInput"

Target site: "System.String Normalize(System.String, System.Text.NormalizationForm) @ System.Text.Normalization"
 
Stack trace "   
at System.Text.Normalization.Normalize(String strInput, NormalizationForm normForm)
   at Klocman.Tools.PathTools.NormalizePath(String path1)
   at Klocman.Tools.PathTools.PathsEqual(String path1, String path2)
   at UninstallTools.Factory.ApplicationEntryTools.AreEntriesRelated(ApplicationUninstallerEntry baseEntry, ApplicationUninstallerEntry otherEntry)
   at UninstallTools.Factory.ApplicationUninstallerFactory.<>c__DisplayClass2_0.<MergeResults>b__0(ApplicationUninstallerEntry x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at UninstallTools.Factory.ApplicationUninstallerFactory.MergeResults(ICollection`1 baseEntries, ICollection`1 newResults, ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetUninstallerEntries(ListGenerationCallback callback)
   at BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater.ListRefreshThread(LoadingDialogInterface dialogInterface)
   at Klocman.Forms.LoadingDialog.<>c__DisplayClass5_0.<.ctor>b__0()"

**Comment by TempUser13** [comment]
is this enough?

**Comment by Klocman** [comment]
Can you send me the KlocTools.dll file from your BCU's directory? I can see that some people keep getting this crash from time to time but I was never able to reproduce it by myself.

**Comment by TempUser13** [comment]
Is there anything else? I won't be at my pc for the next day and a half

**Comment by TempUser13** [comment]
[KlocTools.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2543539/KlocTools.zip)
(it wouldnt let me post the dll so i zipped it up)

**Comment by TempUser13** [comment]
I'll report back on Sunday, thank you

**Comment by TempUser13** [comment]
So I deleted the old dll and put your dll in and it came up with this error on load

![crash 3](https://user-images.githubusercontent.com/44703839/47953323-eb7ef800-df73-11e8-90e4-e171c161b6dc.PNG)

And this is what was copied from the copy button: 

```
"System.MissingMethodException
Method not found: 'Boolean Klocman.Tools.WindowsTools.CheckNetFramework4Installed(Boolean)'.
   at UninstallTools.Factory.StoreAppFactory.<GetUninstallerEntries>d__4.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback)"
```

And the error will come up 5 times but if you click close it will go away and it will load up like normal and I then proceeded to select 13 uninstallers and it threw a error 

![crash4](https://user-images.githubusercontent.com/44703839/47953388-e7070f00-df74-11e8-9fa4-8705b7fc0d01.PNG)

```
Message:
"String contains invalid code poits. Data: 22000000430000003A0000005C00000050000000720000006F0000006700000072000000610000006D0000002000000046000000690000006C00000065000000730000005C0000004D0000006900000063000000720000006F000000760000006900000072000000740000005C0000004D000000450000006D000000750000005C000000750000006E000000690000006E0000007300000074000000610000006C0000006C0000005C000000750000006E000000690000006E0000007300000074000000610000006C0000006C0000002E00000065000000780000006500000022000000200000002D000000750000000000000000000000A8C0000018140000FDFF0000915900000022000000880000010000000000000009000000000000000E000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000088A100004415000088A100004415000018A100004415000018A1000044150000C89F000044150000C89F00004415000000A000004415000000A00000441500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```

```
Target site: 
"System.String SafeNormalize(System.String, System.Text.NormalizationForm) @ Klocman.Extensions.StringExtensions"
```

![crash5](https://user-images.githubusercontent.com/44703839/47953405-233a6f80-df75-11e8-8ac9-5a29f14f2850.PNG)

```
Stack trace:"  
at Klocman.Extensions.StringExtensions.SafeNormalize(String input, NormalizationForm normalizationForm)
   at Klocman.Tools.PathTools.NormalizePath(String path1)
   at Klocman.Tools.PathTools.PathsEqual(String path1, String path2)
   at UninstallTools.Factory.ApplicationEntryTools.AreEntriesRelated(ApplicationUninstallerEntry baseEntry, ApplicationUninstallerEntry otherEntry)
   at BulkCrapUninstaller.Forms.BeginUninstallTaskWizard.<>c__DisplayClass19_0.<GetRelatedUninstallers>b__0(ApplicationUninstallerEntry y)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BulkCrapUninstaller.Forms.BeginUninstallTaskWizard.<Initialize>b__20_1(ApplicationUninstallerEntry x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BulkCrapUninstaller.Forms.BeginUninstallTaskWizard.Initialize(ICollection`1 selectedUninstallers, ICollection`1 allUninstallers, Boolean quiet)
   at BulkCrapUninstaller.Functions.AppUninstaller.RunUninstall(IEnumerable`1 selectedUninstallers, IEnumerable`1 allUninstallers, Boolean quiet)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"
```

![crash 6](https://user-images.githubusercontent.com/44703839/47953441-980da980-df75-11e8-8f77-3b0f476f0de0.PNG)

```
Target site: 
"System.String Normalize(System.String, System.Text.NormalizationForm) @ System.Text.Normalization"
```

```Stack trace: "   
at System.Text.Normalization.Normalize(String strInput, NormalizationForm normForm)
   at Klocman.Extensions.StringExtensions.SafeNormalize(String input, NormalizationForm normalizationForm)"
```
I had 13 uninstallers selected and a few applications selected were already removed without using uninstallers. I tried again with programs which weren't removed 

![crash7](https://user-images.githubusercontent.com/44703839/47953512-a5776380-df76-11e8-8c89-b0ef5e52ff26.PNG)

```
Message:
"String contains invalid code poits. Data: 22000000430000003A0000005C00000050000000720000006F0000006700000072000000610000006D0000002000000046000000690000006C00000065000000730000005C0000004D0000006900000063000000720000006F000000760000006900000072000000740000005C0000004D000000450000006D000000750000005C000000750000006E000000690000006E0000007300000074000000610000006C0000006C0000005C000000750000006E000000690000006E0000007300000074000000610000006C0000006C0000002E00000065000000780000006500000022000000200000002D000000750000000000000000000000A8C0000018140000FDFF0000915900000022000000880000010000000000000009000000000000000E000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000088A100004415000088A100004415000018A100004415000018A1000044150000C89F000044150000C89F00004415000000A000004415000000A00000441500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```

```
Target Site: "
System.String SafeNormalize(System.String, System.Text.NormalizationForm) @ Klocman.Extensions.StringExtensions"
```
![crash8](https://user-images.githubusercontent.com/44703839/47953528-de173d00-df76-11e8-94ff-0edea7545a0e.PNG)

```
Stack trace: 
" at Klocman.Extensions.StringExtensions.SafeNormalize(String input, NormalizationForm normalizationForm)
   at Klocman.Tools.PathTools.NormalizePath(String path1)
   at Klocman.Tools.PathTools.PathsEqual(String path1, String path2)
   at UninstallTools.Factory.ApplicationEntryTools.AreEntriesRelated(ApplicationUninstallerEntry baseEntry, ApplicationUninstallerEntry otherEntry)
   at BulkCrapUninstaller.Forms.BeginUninstallTaskWizard.<>c__DisplayClass19_0.<GetRelatedUninstallers>b__0(ApplicationUninstallerEntry y)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BulkCrapUninstaller.Forms.BeginUninstallTaskWizard.<Initialize>b__20_1(ApplicationUninstallerEntry x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BulkCrapUninstaller.Forms.BeginUninstallTaskWizard.Initialize(ICollection`1 selectedUninstallers, ICollection`1 allUninstallers, Boolean quiet)
   at BulkCrapUninstaller.Functions.AppUninstaller.RunUninstall(IEnumerable`1 selectedUninstallers, IEnumerable`1 allUninstallers, Boolean quiet)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"
```

![crash9](https://user-images.githubusercontent.com/44703839/47953551-22a2d880-df77-11e8-9434-360f49e05e77.PNG)

``` 
Target site: 
"System.String Normalize(System.String, System.Text.NormalizationForm) @ System.Text.Normalization"
```

```
Stack trace: 
"at System.Text.Normalization.Normalize(String strInput, NormalizationForm normForm)
   at Klocman.Extensions.StringExtensions.SafeNormalize(String input, NormalizationForm normalizationForm)
```
Sorry for the long list of words and code

**Comment by Klocman** [comment]
Thank you for the information, I believe I found the issue. Can you check if replacing these files fixes the problem? [Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2545099/Debug.zip)

If the problem still happens, you can only send the "String contains invalid code poits" message and its corresponding stack trace.

**Comment by TempUser13** [comment]
![crash 10](https://user-images.githubusercontent.com/44703839/47954367-8cc07b00-df81-11e8-83c1-542d2e3ff56e.PNG)

**Comment by Klocman** [comment]
Looks like I need to send you the whole build then, here it is: [Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2545110/Debug.zip)

**Comment by TempUser13** [comment]
It didn't throw any crashes at me but the things i uninstalled are still in the to pick list

**Comment by TempUser13** [comment]
I did a unistallation again and it didn't seem to remove any files

**Comment by Klocman** [comment]
This is a debug build that has "Simulate uninstallation" enabled by default. You need to disable this in uninstallation options before starting the uninstall (second to last step).

**Comment by TempUser13** [comment]
Ah I didn't realise but other than that there werent any issues, thanks

**Comment by Klocman** [comment]
Good to hear it's fixed. The issue was invalid/corrupted data in registry. Most likely related to this https://blogs.msdn.microsoft.com/oldnewthing/20040824-00/?p=38063/

This case is now being handled by cutting off the invalid part of all strings read from registry.
