### ISSUE TITLE
System.Security.SecurityException Requested registry access is not allowed.

### ISSUE THREAD

**Issue by Mintonne** [Klocman/Bulk-Crap-Uninstaller#234]
Hey,

I keep getting the error below just before the registry scan begins. (This has happened twice so far)

```
System.Security.SecurityException
Requested registry access is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at UninstallTools.Junk.Finders.Registry.ComScanner.GetClsidEntries(ICollection`1 results, RegistryKey classes)
   at UninstallTools.Junk.Finders.Registry.ComScanner.Setup(ICollection`1 allUninstallers)
   at UninstallTools.Junk.JunkManager.FindJunk(IEnumerable`1 targets, ICollection`1 allUninstallers, ListGenerationCallback progressCallback)
   at BulkCrapUninstaller.Functions.AppUninstaller.<>c__DisplayClass19_0.<SearchForAndRemoveJunk>b__0(LoadingDialogInterface dialogInterface)
   at Klocman.Forms.LoadingDialog.<>c__DisplayClass5_0.<.ctor>b__0()
```

The UAC dialog did appear and I accepted the requested permissions. BCU is currently installed in Program Files.

**Comment by Klocman** [comment]
I fixed it in 8a56e1884c8fbcf4b3f5b7fa5a1260ed8c7b6a6f, you can compile from source or wait for the next release to get the fix.
