### ISSUE TITLE
System.FormatException Error / Crash at start up

### ISSUE THREAD

**Issue by Angerreign** [Klocman/Bulk-Crap-Uninstaller#237]
![2019-08-03 19_38_44-Bulk Crap Uninstaller Documentation](https://user-images.githubusercontent.com/36768953/62414734-4db27980-b628-11e9-84e7-738b8c8d8d89.jpg)
![2019-08-03 19_39_46-Bulk Crap Uninstaller Documentation](https://user-images.githubusercontent.com/36768953/62414735-4f7c3d00-b628-11e9-8235-1192f45e2abd.jpg)

I cannot start up BCUninstaller. I tried reinstall etc.

**Comment by Klocman** [comment]
Hello!

Can you copy the entire Stack Trace field and send it to me? It's on the
Exception tab.


Best regards,
Marcin

**Comment by Angerreign** [comment]
at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at BulkCrapUninstaller.Forms.MainWindow.RefreshStatusbarTotalLabel(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at BrightIdeasSoftware.ObjectListView.OnAfterSorting(AfterSortingEventArgs e)
   at BrightIdeasSoftware.ObjectListView.Sort(OLVColumn columnToSort, SortOrder order)
   at BrightIdeasSoftware.ObjectListView.BuildList(Boolean shouldPreserveState)
   at BrightIdeasSoftware.ObjectListView.SetObjects(IEnumerable collection, Boolean preserveState)
   at BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater.<>c__DisplayClass31_0.<InitiateListRefresh>g__OnRefreshFinished|0(Object sender, FormClosedEventArgs args)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Klocman** [comment]
I think I found the issue, can you try replacing your tr folder with this
one? https://www.dropbox.com/s/541ahvxs54byfjh/tr.zip?dl=0


Best regards,
Marcin

**Comment by Angerreign** [comment]
Thanks. It worked!
