### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 2832167832** [Klocman/Bulk-Crap-Uninstaller#371]
System.PlatformNotSupportedException
Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
   at System.Management.WmiNetUtilsHelper.<>c__DisplayClass104_0.<LoadPlatformNotSupportedDelegates>b__39(Int32 _, IntPtr __, APTTYPE& ___)
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.ManagementScope..ctor(String path)
   at System.Management.ManagementObjectSearcher..ctor(String scope, String queryString)
   at UninstallTools.Startup.Service.ServiceEntryFactory.GetServiceEntries()
   at UninstallTools.Startup.StartupManager.<>c.<.cctor>b__0_3()
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetUninstallerEntries(ListGenerationCallback callback)

**Comment by Klocman** [comment]
Fixed in upcoming release.
