### ISSUE TITLE
Crash durring startup, program is not useable (Uncaught exception in ListRefreshThread)

### ISSUE THREAD

**Issue by TheKing4562** [Klocman/Bulk-Crap-Uninstaller#392]
#324 

![BCUninstaller_ODL1sovQGM](https://user-images.githubusercontent.com/109390785/179314112-f7f68ea0-2fed-45e6-b376-55ddb14172d2.png)
![BCUninstaller_lGzshzkXFQ](https://user-images.githubusercontent.com/109390785/179314128-485e35ac-be94-4455-bfc3-6b1b31addbbb.png)

Hi, I'm a new user so I'm not sure I'm formatting things right here. Also I have no relations to anyone in the previous thread but I am having the exact same issue as them. Also going through old version at the moment to see if I can get a functional release but encountering the same error, not sure if that's any help. At the time of writing last version I tried and had no success in was v3.22, I skipped a good handful builds between late 2018 and 2017.

**Comment by TheKing4562** [comment]
Maybe my anti-virus is eating away the ability for the crash reports to be sent. Going to try the manual way.
From installed via winget version:
[BCUninstaller.log](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/9139240/BCUninstaller.log)
From Portable version:
[BCUninstaller.log](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/9139244/BCUninstaller.log)

Reading it myself it seams in both scenarios it might be something with the Uplay client, not sure how to fix it tho without ripping out the client cleanly somehow.

**Comment by Klocman** [comment]
The logs don't seem to show the real cause of the issue, the uplay crash is handled properly and is of different type.

If there is no report zip file generated in BCU directory then paste the full contents of the Stack Trace field under the Exception tab in the crash box. Make sure to paste stack traces of all exceptions (switch exceptions in the list at the top).

**Comment by TheKing4562** [comment]
Will do...
![BCUninstaller_BhCsHQ2In9](https://user-images.githubusercontent.com/109390785/180087258-1e22c157-dd60-4948-aa31-58b6e4901b91.png)
From: System.Exception

Target Site: Void <InitiateListRefresh>g__OnRefreshFinished|0(System.Object, System.Windows.Forms.FormClosedEventArgs) @ BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater+<>c__DisplayClass31_0

Stack Trace:  
  at BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater.<>c__DisplayClass31_0.<InitiateListRefresh>g__OnRefreshFinished|0(Object sender, FormClosedEventArgs args)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at Klocman.Forms.LoadingDialog.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


![BCUninstaller_JSg91EWVkL](https://user-images.githubusercontent.com/109390785/180087359-771c8df6-23b4-40fc-a03c-8fa9be27f514.png)
From: System.IO.InvalidDataException

Message: String contains invalid characters. Data: 430000003A0000005C00000055000000730000006500000072000000730000005C0000004D0000006100000073000000740000006500000072000000200000006100000063000000630000006F000000750000006E000000740000005C000000410000007000000070000000640000006100000074000000610000005C000000520000006F000000610000006D000000690000006E000000670000005C000000FDFF000041000000640000006F0000006200000065000000

Target Site: System.String SafeNormalize(System.String, System.Text.NormalizationForm) @ Klocman.Extensions.StringExtensions

Stack Trace: 
   at Klocman.Extensions.StringExtensions.SafeNormalize(String input, NormalizationForm normalizationForm)
   at Klocman.Tools.PathTools.NormalizePath(String path1)
   at Klocman.Tools.PathTools.PathsEqual(String path1, String path2)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Klocman.Extensions.CollectionExtensions.Distinct[TSource](IEnumerable`1 source, Func`3 equalityComparator)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UninstallTools.Factory.DirectoryFactory.GetUninstallerEntries(ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetUninstallerEntries(ListGenerationCallback callback)
   at BulkCrapUninstaller.Functions.ApplicationList.UninstallerListViewUpdater.ListRefreshThread(LoadingDialogInterface dialogInterface)
   at Klocman.Forms.LoadingDialog.<>c__DisplayClass5_0.<.ctor>b__0()


![BCUninstaller_PdPbLnLmio](https://user-images.githubusercontent.com/109390785/180087382-e1e3495b-2fda-48bb-a392-510eb3b7088c.png)
From: System.ArgumentException

Message: String contains invalid Unicode code points. (Parameter 'strInput')

Target Site: Void ValidateArguments(System.String, System.Text.NormalizationForm) @ System.Globalization.Normalization

Stack Trace: 
   at System.Globalization.Normalization.ValidateArguments(String strInput, NormalizationForm normalizationForm)
   at System.Globalization.Normalization.IcuNormalize(String strInput, NormalizationForm normalizationForm)
   at Klocman.Extensions.StringExtensions.SafeNormalize(String input, NormalizationForm normalizationForm)

**Comment by Klocman** [comment]
Weird, it crashes trying to parse a folder name inside of `C:\Users\Master account\Appdata\Roaming\`. Can you check if you have any unusual-looking folders inside of there?

**Comment by TheKing4562** [comment]
Got some weird folders named: �Adobe (from 2013), �Adobe from (2013 again?), and �Adobe (from 2015). I can try deleting them and launching the program again. Also tried copy pasting the names but it seams the names are some sort of null?
I'm gonna try holding off from 100% removing the files in-case you want the exact names.
![explorer_3xjrsYoyQC](https://user-images.githubusercontent.com/109390785/182466947-48949c3c-1039-4866-8689-3ab48c68e7af.png)
