### ISSUE TITLE
scoop json error

### ISSUE THREAD

**Issue by aetonsi** [Klocman/Bulk-Crap-Uninstaller#498]
Hi,
i don't know exactly how BCU analyzes the scoop packages, but since the day i installed scoop, when BCU scans my system it reports a JSON error during the scoop phase:
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/18366087/65e3feda-4567-4de7-bdd3-0c251378f263)

```log
System.Text.Json.JsonException
'W' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at UninstallTools.Factory.ScoopFactory.GetUninstallerEntries(ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback)

Inner: 
System.Text.Json.JsonReaderException
'W' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

My `scoop -v` output:
```log
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
8bc4007c3 winrar: Update to version 6.22

'main' bucket:
ec72ab311 wuzz: Update to version 0.5.0
```

My `scoop list` output:
```log
Installed apps:

Name                   Version       Source Updated             Info
----                   -------       ------ -------             ----
7zip                   22.01         main   2023-05-30 16:21:29 
fancontrol             157           extras 2023-05-31 12:55:01 
vcredist2022           14.36.32532.0 extras 2023-05-30 16:24:34 
windowsdesktop-runtime 7.0.5         extras 2023-05-31 12:55:37 
xampp                  8.2.4-0       extras 2023-05-30 16:23:50 
```

have a nice day

**Comment by Klocman** [comment]
Update BCUninstaller. If that doesn't help, update Scoop. If that doesn't help, send output of `scoop export`.

**Comment by aetonsi** [comment]
i checked the json syntax and it seems to be fine, or at both least javascript's `JSON.parse` and php's `json_decode` do not throw...

<details>
<summary>BCU</summary>

![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/18366087/b2abc9ec-a862-40cf-8841-b21ff67c297d)
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/18366087/34b4e483-8198-4bd0-aa31-cb33a8e765cf)
</details>

<details>
<summary>JSON</summary>

```json
{
    "apps": [
        {
            "Info": "",
            "Source": "main",
            "Name": "7zip",
            "Version": "22.01",
            "Updated": "2023-05-30T16:21:29.1938105+02:00"
        },
        {
            "Info": "",
            "Source": "extras",
            "Name": "fancontrol",
            "Version": "157",
            "Updated": "2023-05-31T12:55:01.669674+02:00"
        },
        {
            "Info": "",
            "Source": "extras",
            "Name": "vcredist2022",
            "Version": "14.36.32532.0",
            "Updated": "2023-05-30T16:24:34.633685+02:00"
        },
        {
            "Info": "",
            "Source": "extras",
            "Name": "windowsdesktop-runtime",
            "Version": "7.0.5",
            "Updated": "2023-05-31T12:55:37.1199758+02:00"
        },
        {
            "Info": "",
            "Source": "extras",
            "Name": "xampp",
            "Version": "8.2.4-0",
            "Updated": "2023-05-30T16:23:50.0437206+02:00"
        }
    ],
    "buckets": [
        {
            "Name": "extras",
            "Source": "https://github.com/ScoopInstaller/Extras",
            "Updated": "2023-05-31T10:27:13+02:00",
            "Manifests": 1865
        },
        {
            "Name": "main",
            "Source": "https://github.com/ScoopInstaller/Main.git",
            "Updated": "2023-05-31T10:27:59+02:00",
            "Manifests": 1200
        }
    ]
}
```
</details>

**Comment by Klocman** [comment]
The JSON you pasted works fine for me, BCU parses it correctly. If you're on BCU v5.6 then it shouldn't be possible for JsonException to happen. Try making a clean install or manually replace the portable version and replace all old files.

**Comment by aetonsi** [comment]
Uninstall and installed again (i'm using choco). Still happening.
Downloaded portable zip and unzipped in `C:\Program Files\BCUninstaller`. Still happening.

I think i know why. You're running `scoop export` in a `powershell.exe` shell, right?
My powershell's `$PROFILE` file prints a `Welcome ...` message. I think BCU is getting that message in the command output, and it breaks the JSON content.
If that's the case, adding the `-noprofile` switch fixes the problem

**Comment by Klocman** [comment]
That indeed seems to be the issue, thanks for letting me know.
Can you check if this build fixes the issue? [net6.0-windows10.0.18362.0.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/11913458/net6.0-windows10.0.18362.0.zip)

**Comment by aetonsi** [comment]
Yes that works
