### ISSUE TITLE
Launch Error causing freezing, making program unusable: System.Text.Json.JsonException

### ISSUE THREAD

**Issue by nsde** [Klocman/Bulk-Crap-Uninstaller#552]
Windows 10 x64 | BCU v.5.6 & v5.7 x64 [SETUP] | AMD CPU

## How to reproduce
- Install *non*-portable version
- I have used prior versions of the software (pretty sure I have updated the software without any issues before)
- I updated to v5.7 and the error occurred

## Workaround
- v5.6 PORTABLE seems to work fine

**File:**
BCUninstaller.dll [5.7.0.0] - This error also occurs in version 5.6

**Exception**
'C' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

**Target Site**
Void ReThrowWithPath(System.Text.Json.ReadStack ByRef, System.Text.Json.JsonReaderException) @ System.Text.Json.ThrowHelper

**NBug:** 1.2.0.0
**CLR:** 6.0.22

![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/67185896/418d4bc9-06e2-40d1-8d8c-15b5c7db2179)
![image](https://github.com/Klocman/Bulk-Crap-Uninstaller/assets/67185896/ab958303-d92f-44b0-b667-1a0bc9f77a96)

**Comment by Klocman** [comment]
Did you try a clean install of v5.7? Does it show the same error?

**Comment by Klocman** [comment]
Get the portable version and extract it to a completely new directory.

**Comment by hsopen** [comment]
(This is Google Translate) Have you solved it? I also had a similar error. Finally, I ran  `scoop export` and found that there was a problem with one of the buckets. I deleted the bucket and then re-imported it, and the problem was solved.

**Comment by PabloGrok** [comment]
I'm having this issue as well. Here's the copied error text:

System.Text.Json.JsonException
'G' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at UninstallTools.Factory.ScoopFactory.GetUninstallerEntries(ListGenerationCallback progressCallback)
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback)

Inner: 
System.Text.Json.JsonReaderException
'G' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

I tried running the portable version from a different directory and the result is the same.  Please let me know if I can do anything to provide more info.
