### ISSUE TITLE
Windows 7 x64 issue

### ISSUE THREAD

**Issue by i300220** [Klocman/Bulk-Crap-Uninstaller#67]
This issue froze v. 3.8 so I downgraded to v. 3.7.2.  The issue is still present but manageable if one clicks on OK/Copy/Details

Here's what I copied from v. 3.7.2:

_BCUninstaller, Version=3.7.2.28791, Culture=neutral, PublicKeyToken=null | MSIL | Microsoft Windows NT 6.1.7600.0 | 64bit
System.IO.IOException
Error while collecting Windows Features, try restarting your computer. If the error persists read the KB957310 article.
   at UninstallTools.Factory.WindowsFeatureFactory.GetUninstallerEntries()
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries()

Inner: 
System.Runtime.InteropServices.COMException

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectSearcher.Get()
   at Klocman.IO.WmiQueries.GetWindowsFeatures()
   at UninstallTools.Factory.WindowsFeatureFactory.<>c__DisplayClass0_0.<GetUninstallerEntries>b__0()
   _

I followed all the 4 steps in the kb957310 article.  Didn't help.
![kb957310article](https://cloud.githubusercontent.com/assets/15702355/25026060/bea48d70-2072-11e7-8965-41ea07fae1aa.jpg)

**Comment by Klocman** [comment]
It's a known issue, sadly. Some Windows installs take forever or just outright fail when accessing features through WMI. 

I've tried to lessen the issue, but I think the only real fix is to put enumerating windows features (and probably windows updates in the newest version) as an option in the settings that is off by default.

**Comment by i300220** [comment]
Windows being windows,  I'm looking forward for that option.

Strangely I have not that issue on my win 7 sp1 box.

Congrats and thanks for that wonderful piece of software BTW!
