### ISSUE TITLE
Startup frozen @ "Finishing up."

### ISSUE THREAD

**Issue by Klocman** [Klocman/Bulk-Crap-Uninstaller#83]
> I installed BCUninstaller_3.12_setup.exe, but it's been > 30 min everytime I try to start program, while frozen @ "Finishing up." I never get past that.
> 
> Win10 x64, all latest updates

**Comment by Klocman** [comment]
Sent in by @TPS.

Can you send the the .log file, if it's saved?

**Comment by TPS** [comment]
I'd love to.  Where is it?

**Comment by Klocman** [comment]
It's in BCU's directory, called BCUninstaller.log.

**Comment by TPS** [comment]
Entire contents as follows:
````
--------------------------------------------------
1:04:34A - Application startup
--------------------------------------------------
1:40:39P - Application startup
1:41:05P - MySql.Data.MySqlClient.MySqlException: Error writing file '/tmp/MY0lSrOM' (Errcode: 28)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at BulkCrapUninstaller.Functions.Ratings.UninstallerRatingManager.FetchRatings()
   at BulkCrapUninstaller.Functions.UninstallerListViewTools.<ProcessRatingsInitialize>b__39_0()
--------------------------------------------------
12:28:05A - Application startup
--------------------------------------------------
2:41:44A - Application startup
--------------------------------------------------
3:27:48A - Application startup
--------------------------------------------------
4:03:24A - Application startup
````

**Comment by Klocman** [comment]
Are you using the newest version? Download a fresh install in case your old one is corrupted.

**Comment by TPS** [comment]
That was the latest _(see above)_, but redownloading/reinstalling via [DTA](https://www.downthemall.net/)'s checksummed download seems to have solved it.  I guess downloading via Chromium didn't work right.

Thanks for troubleshooting this for me!
